source:
  type: snowflake
  serviceName: snowflake-code
  serviceConnection:
    config:
      type: Snowflake
      username: ${SNOWFLAKE_USERNAME}
      password: ${SNOWFLAKE_PASSWORD}
      warehouse: ${SNOWFLAKE_WAREHOUSE}
      account: ${SNOWFLAKE_ACCOUNT}
      database: ${SNOWFLAKE_DATABASE}
      includeTransientTables: ${SNOWFLAKE_INCLUDE_TRANSIENT_TABLES}
      includeStreams: ${SNOWFLAKE_INCLUDE_STREAMS}
      clientSessionKeepAlive: ${SNOWFLAKE_CLIENT_SESSION_KEEP_ALIVE}
      privateKey: ${SNOWFLAKE_PRIVATE_KEY}
      snowflakePrivatekeyPassphrase: ${SNOWFLAKE_PRIVATE_KEY_PASSPHRASE}
      role: ${SNOWFLAKE_ROLE}

  sourceConfig:
    config:
      type: DatabaseMetadata
      markDeletedTables: true
      markDeletedStoredProcedures: true
      includeTables: true
      includeViews: true
sink:
  type: metadata-rest
  config: {}
workflowConfig:
  loggerLevel: INFO
  openMetadataServerConfig:
    hostPort: ${OPENMETADATA_SERVER_HOST_PORT}
    authProvider: openmetadata
    securityConfig:
      jwtToken: ${OPENMETADATA_JWT_TOKEN}
    storeServiceConnection: true
